spring.application.name=ProductService

spring.datasource.url=jdbc:mysql://localhost:3306/product_service
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cloudinary.cloud-name=inb9pp2y
cloudinary.api-key=672982624469266
cloudinary.api-secret=8eF8cc2GcuDnDC-K4ggHH30riro
